namespace Godot.SourceGenerators;

internal enum PropertyHint
{
    None = 0,
    Range = 1,
    Enum = 2,
    EnumSuggestion = 3,
    ExpEasing = 4,
    Link = 5,
    Flags = 6,
    Layers2DRender = 7,
    Layers2DPhysics = 8,
    Layers2DNavigation = 9,
    Layers3DRender = 10,
    Layers3DPhysics = 11,
    Layers3DNavigation = 12,
    File = 13,
    Dir = 14,
    GlobalFile = 15,
    GlobalDir = 16,
    ResourceType = 17,
    MultilineText = 18,
    Expression = 19,
    PlaceholderText = 20,
    ColorNoAlpha = 21,
    ObjectId = 22,
    TypeString = 23,
    NodePathToEditedNode = 24,
    ObjectTooBig = 25,
    NodePathValidTypes = 26,
    SaveFile = 27,
    GlobalSaveFile = 28,
    IntIsObjectid = 29,
    IntIsPointer = 30,
    ArrayType = 31,
    LocaleId = 32,
    LocalizableString = 33,
    NodeType = 34,
    HideQuaternionEdit = 35,
    Password = 36,
    LayersAvoidance = 37,
    DictionaryType = 38,
    ToolButton = 39,
    Max = 40
}