using System;
using System.Threading;

namespace Godot.SourceGenerators.MemberCaching;

public record FileHeaderComment : IWritable
{
    public string? GenName { get; init; }
    public DateTime GenTime { get; init; }
    public string? GenVersion { get; init; }
    public ValueArray<string> FilenameSources { get; init; }
    public string? Description { get; init; }

    /// <inheritdoc />
    public void Write(FormatWriter writer, CancellationToken cancellationToken = default)
    {
        const string start = "/* ";
        const string end = " */";
        const string indent = " * ";
        const string seperator = "\n";
        const string autoGenTag = "<auto-generated/>";

        writer.WriteLine(start);
        writer.PushIndent(indent);
        writer.WriteLine(autoGenTag);
        writer.WriteLine("This file is auto-generated by the Godot source generator.");
        writer.WriteLine(string.Empty);
        writer.WriteIfNoneNullOrEmpty("Tool Name: ", GenName, writer.NewLine);
        writer.WriteIfNoneNullOrEmpty("Tool Version: ", GenVersion, writer.NewLine);
        writer.WriteIfNone(
            InvalidValueKindFlags.DefaultValue,
            "Generated at: ",
            GenTime.ToString("F", writer.Culture),
            writer.NewLine
        );
        writer.WriteIfNoneNullOrEmpty("Source Files: ", string.Join(", ", FilenameSources));

        if (!string.IsNullOrWhiteSpace(Description))
        {
            writer.WriteLine(seperator);
            writer.WriteLine(Description);
        }

        writer.PopIndent();
        writer.WriteLine(end);
    }
}